import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  workflowsSidebar: [
    {
      type: 'category',
      label: 'Workflows',
      link: {type: 'doc', id: 'workflows/index'},
      items: [
        {
          type: 'category',
          label: 'Clinical Workflows',
          link: {type: 'doc', id: 'workflows/clinical/index'},
          items: [{type: 'autogenerated', dirName: 'workflows/clinical'}],
        },
        {
          type: 'category',
          label: 'Administration Workflows',
          link: {type: 'doc', id: 'workflows/administration/index'},
          items: [{type: 'autogenerated', dirName: 'workflows/administration'}],
        },
        {
          type: 'category',
          label: 'Operations Workflows',
          link: {type: 'doc', id: 'workflows/operations/index'},
          items: [{type: 'autogenerated', dirName: 'workflows/operations'}],
        },
      ],
    },
  ],

  canvasPlatformSidebar: [
    {
      type: 'category',
      label: 'Canvas Platform',
      link: {type: 'doc', id: 'canvas-platform/index'},
      items: [
        {
          type: 'category',
          label: 'Architecture',
          link: {type: 'doc', id: 'canvas-platform/architecture/index'},
          items: [{type: 'autogenerated', dirName: 'canvas-platform/architecture'}],
        },
        {
          type: 'category',
          label: 'Data Model',
          link: {type: 'doc', id: 'canvas-platform/data-model/index'},
          items: [{type: 'autogenerated', dirName: 'canvas-platform/data-model'}],
        },
        {
          type: 'category',
          label: 'Configuration',
          link: {type: 'doc', id: 'canvas-platform/configuration/index'},
          items: [{type: 'autogenerated', dirName: 'canvas-platform/configuration'}],
        },
        {
          type: 'category',
          label: 'UI/UX',
          link: {type: 'doc', id: 'canvas-platform/ui-ux/index'},
          items: [{type: 'autogenerated', dirName: 'canvas-platform/ui-ux'}],
        },
      ],
    },
  ],

  fhirDataSidebar: [
    {
      type: 'category',
      label: 'FHIR & Data',
      link: {type: 'doc', id: 'fhir-data/index'},
      items: [
        {
          type: 'category',
          label: 'FHIR Resources',
          link: {type: 'doc', id: 'fhir-data/fhir-resources/index'},
          items: [{type: 'autogenerated', dirName: 'fhir-data/fhir-resources'}],
        },
        {
          type: 'category',
          label: 'Terminology',
          link: {type: 'doc', id: 'fhir-data/terminology/index'},
          items: [{type: 'autogenerated', dirName: 'fhir-data/terminology'}],
        },
      ],
    },
  ],

  technicalSidebar: [
    {
      type: 'category',
      label: 'Technical',
      link: {type: 'doc', id: 'technical/index'},
      items: [
        {
          type: 'category',
          label: 'Plugins & API',
          link: {type: 'doc', id: 'technical/plugins-api/index'},
          items: [{type: 'autogenerated', dirName: 'technical/plugins-api'}],
        },
      ],
    },
  ],

  regulatorySidebar: [
    {
      type: 'category',
      label: 'Regulatory',
      link: {type: 'doc', id: 'regulatory/index'},
      items: [{type: 'autogenerated', dirName: 'regulatory'}],
    },
  ],
};

export default sidebars;
